#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

npm run lint
linting_result=$?

if [ $linting_result -ne 0 ]; then
  echo "Lint falhou; corrigir os problemas apontados antes de commitar."
  echo $linting_result
  exit 1
fi

